# Generated by Django 4.1 on 2022-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='myplaces/static/places_pictures/default.png', upload_to='myplaces/static/places_pictures'),
        ),
    ]
